### PR TITLE
Use cargo metadata to find binary to flash

### LINKED ISSUE #3: Detect when cargo flash is used for a library project
When cargo-flash is executed in a library project, it currently fails with the following output:

```console
$ cargo flash --chip nrf5182
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
    Flashing /home/dominik/Coding/fomu-rt/target/debug/fomu-rt
error: failed to flash /home/dominik/Coding/fomu-rt/target/debug/fomu-rt: No such file or directory (os error 2)
```

We should detect when the user tries to flash a library, and show a better error message indicating that flashing a library does not work.

### LINKED ISSUE #4: `cargo flash` does not work inside members of a workspace
It looks for `target` in the current directory, but in a workspace `target` is in the workspace root, resulting in a panic like this:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
```

### LINKED ISSUE #5: Detect when cargo-flash is run in a workspace
When cargo flash is run in a workspace, the following error message is shown:

    error: failed to parse Cargo project information: missing field `package`

This message is not very helpful, we should detect this case and show a better error message.

### PR DESCRIPTION
**Pull request by Tiwalun**
This PR improves the detection of the appropriate binary to flash.

It switches from `cargo-project` to `cargo-metadata`, and now processes the machine-readable output of `cargo build`.
This makes it more robust, as the behaviour should now be identical to `cargo run`, or at least as close as possible.

The following bugs should be fixed:

* Fix #3, an error message is now shown in library crates.
* Fix #4, running cargo flash in a workspace now works the same as cargo run, meaning it works if a single binary is found,
  otherwise a binary has to be manually selected. (Also fixes #5)

Bug #40 might be fixed as well.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+            // Ignore other messages
+            _ => (),
+        }
+    }
+
+    if let Some(artifact) = target_artifact {
+        // Unwrap is safe, we only store artifacts with an executable
+        Ok(artifact.executable.unwrap())
+    } else {
+        // We did not find a binary, so we should return an error
```
Comment (Yatekii) [inline src/lib.rs:103]:
```suggestion
        // We did not find a binary, so we should return an error.
```

File: src/lib.rs [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+                    print!("{}", rendered);
+                }
+            }
+            // Ignore other messages
+            _ => (),
+        }
+    }
+
+    if let Some(artifact) = target_artifact {
+        // Unwrap is safe, we only store artifacts with an executable
```
Comment (Yatekii) [inline src/lib.rs:100]:
```suggestion
        // Unwrap is safe, we only store artifacts with an executable.
```

File: src/lib.rs [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+                        target_artifact = Some(artifact);
+                    }
+                }
+            }
+            Message::CompilerMessage(message) => {
+                if let Some(rendered) = message.message.rendered {
+                    print!("{}", rendered);
+                }
+            }
+            // Ignore other messages
```
Comment (Yatekii) [inline src/lib.rs:94]:
```suggestion
            // Ignore other messages.
```

File: src/lib.rs [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+        return Err(anyhow!(
+            "Failed to run cargo build: exit code = {:?}",
+            output.status.code()
+        ));
+    }
+
+    // parse build output
+    let messages = Message::parse_stream(&output.stdout[..]);
+
+    // find artifacts
```
Comment (Yatekii) [inline src/lib.rs:70]:
```suggestion
    // Find artifacts.
```

File: src/lib.rs [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+    let output = cargo_command.wait_with_output()?;
+
+    if !output.status.success() {
+        return Err(anyhow!(
+            "Failed to run cargo build: exit code = {:?}",
+            output.status.code()
+        ));
+    }
+
+    // parse build output
```
Comment (Yatekii) [inline src/lib.rs:67]:
```suggestion
    // Parse build output.
```

File: src/lib.rs [hunk 6]
```diff
@@ -0,0 +1,110 @@
...
+///
+/// `args` will be passed to cargo build, and `--message-format json` will be
+/// added to the list of arguments.
+///
+/// The output of `cargo build` is parsed to detect the path to the generated binary artifact.
+/// If either no artifact, or more than a single artifact are created, an error is returned.
+pub fn build_artifact(work_dir: &Path, args: &[String]) -> Result<PathBuf> {
+    let cargo_executable = std::env::var("CARGO").unwrap_or("cargo".to_owned());
+
+    // Build the project
```
Comment (Yatekii) [inline src/lib.rs:49]:
```suggestion
    // Build the project.
```
